/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ActivityAction = "assigned" | "commented" | "completed" | "created" | "deleted" | "status_changed" | "updated";

export type BudgetItemStatus = "contracted" | "paid" | "pending";

export type CampaignStatus = "active" | "approved" | "completed" | "draft";

export type CampaignType = "awareness" | "brand_engagement" | "corporate_event" | "product_launch" | "seasonal_promotion";

export type DependencyType = "finish_to_finish" | "finish_to_start" | "start_to_finish" | "start_to_start";

export type EmploymentType = "clt" | "contract_service" | "hourly_contractor";

export type ExecutionStatus = "completed" | "in_progress" | "paused";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type InitiativeStatus = "aprovada" | "concluida" | "em_andamento" | "recusada" | "solicitada";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type PlanningBaseType = "annual" | "custom" | "quarterly";

export type ProjectCategory = "custom" | "event" | "implementation" | "infrastructure" | "maintenance" | "operational" | "strategic" | "travel";

export type ProjectStatus = "active" | "cancelled" | "completed" | "paused";

export type SectorMemberRole = "agente" | "responsavel";

export type StageStatus = "completed" | "in_progress" | "pending";

export type TaskActionStatus = "completed" | "in_progress" | "pending" | "rejected";

export type TaskActionType = "approve" | "confirm_completion" | "custom" | "make_payment" | "review" | "sign_document";

export type TaskParticipantRole = "assignee" | "observer" | "owner" | "reviewer";

export type TaskPriority = "critical" | "high" | "low" | "medium";

export type TaskShift = "afternoon" | "morning" | "night";

export type TaskStatus = "blocked" | "completed" | "in_progress" | "open" | "overdue" | "standby";

export type TeamMemberStatus = "active" | "pending_registration";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface ActivityLogs {
  action: ActivityAction;
  entityId: string;
  entityType: string;
  fieldChanged: string | null;
  id: string;
  metadata: Generated<Json | null>;
  newValue: string | null;
  oldValue: string | null;
  performedAt: Generated<Timestamp | null>;
  performedBy: string | null;
  projectId: string | null;
}

export interface Brands {
  address: Generated<string | null>;
  city: Generated<string | null>;
  companyName: Generated<string>;
  contactName: Generated<string | null>;
  createdAt: Generated<Timestamp | null>;
  email: Generated<string | null>;
  id: Generated<number>;
  logoAdColor: Generated<string | null>;
  logoAdOpacity: Generated<Numeric | null>;
  logoBgColor: Generated<string | null>;
  logoBgOpacity: Generated<Numeric | null>;
  logoPlusColor: Generated<string | null>;
  logoPlusOpacity: Generated<Numeric | null>;
  phone: Generated<string | null>;
  primaryColor: Generated<string | null>;
  role: Generated<string | null>;
  secondaryColor: Generated<string | null>;
  updatedAt: Generated<Timestamp | null>;
  website: Generated<string | null>;
  zip: Generated<string | null>;
}

export interface BudgetItems {
  category: string;
  contractedAmount: Generated<Numeric | null>;
  createdAt: Generated<Timestamp | null>;
  description: Generated<string | null>;
  dueDate: Timestamp | null;
  id: string;
  paidAmount: Generated<Numeric | null>;
  predictedAmount: Generated<Numeric | null>;
  projectId: string;
  status: Generated<BudgetItemStatus | null>;
  vendor: Generated<string | null>;
}

export interface CampaignPosts {
  campaignId: string;
  channel: Generated<string | null>;
  content: Generated<string | null>;
  createdAt: Generated<Timestamp | null>;
  id: string;
  scheduledDate: Timestamp | null;
  title: string;
}

export interface Campaigns {
  channels: Generated<string[] | null>;
  createdAt: Generated<Timestamp | null>;
  dna_direcao: Generated<string | null>;
  dna_experiencia: Generated<string | null>;
  dna_modulos: Generated<any | null>;
  duration: Generated<number>;
  id: string;
  name: string;
  objective: Generated<string | null>;
  status: Generated<CampaignStatus | null>;
  targetAudience: Generated<string | null>;
  type: CampaignType;
  updatedAt: Generated<Timestamp | null>;
}

export interface Executions {
  createdAt: Generated<Timestamp | null>;
  durationMinutes: number | null;
  endedAt: Timestamp | null;
  id: Generated<string>;
  notes: string | null;
  operatorId: string;
  startedAt: Generated<Timestamp>;
  status: Generated<ExecutionStatus>;
  taskActionId: string;
}

export interface Initiatives {
  assignedTeamId: string | null;
  context: string | null;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  endDate: Timestamp | null;
  id: Generated<string>;
  name: string;
  responsibleId: string | null;
  sectorId: string | null;
  solicitanteId: string | null;
  startDate: Timestamp | null;
  status: Generated<InitiativeStatus>;
  type: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean>;
}

export interface Modules {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: string;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface ModuleStages {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: string;
  moduleId: string;
  name: string;
  sortOrder: Generated<number>;
}

export interface ModuleTasks {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: string;
  moduleStageId: string;
  name: string;
  priority: Generated<TaskPriority>;
  sortOrder: Generated<number>;
}

export interface PlanningBaseItems {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: string;
  name: string;
  planningBaseId: string;
  projectIdea: string | null;
  sortOrder: Generated<number>;
}

export interface PlanningBases {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: string;
  name: string;
  type: Generated<PlanningBaseType>;
  updatedAt: Generated<Timestamp>;
}

export interface ProjectChecklistItems {
  categoryKey: Generated<string>;
  completedAt: Timestamp | null;
  completedBy: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: string;
  isCompleted: Generated<boolean>;
  projectId: string;
  sortOrder: Generated<number>;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Projects {
  assignedTeamId: string | null;
  budget: Generated<Numeric | null>;
  category: Generated<ProjectCategory | null>;
  createdAt: Generated<Timestamp | null>;
  description: Generated<string | null>;
  endDate: Timestamp | null;
  id: string;
  initiativeId: string;
  name: string;
  ownerId: string | null;
  priority: Generated<TaskPriority | null>;
  startDate: Timestamp;
  status: Generated<ProjectStatus | null>;
  tags: Generated<string[] | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface ProjectStages {
  assignedTeamId: string | null;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  endDate: Timestamp | null;
  id: Generated<string>;
  name: string;
  projectId: string;
  sortOrder: Generated<number>;
  startDate: Timestamp | null;
  status: Generated<StageStatus>;
  updatedAt: Generated<Timestamp | null>;
}

export interface SectorMembers {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  memberId: string;
  permissions: Generated<Json>;
  role: Generated<SectorMemberRole>;
  sectorId: string;
}

export interface Sectors {
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp>;
  userId: number;
}

export interface TaskActions {
  actualHours: Numeric | null;
  assignedTo: string | null;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  dueDate: Timestamp | null;
  estimatedHours: Numeric | null;
  id: string;
  operatorId: string | null;
  requestedBy: string | null;
  status: Generated<TaskActionStatus>;
  taskId: string;
  title: string;
  type: Generated<TaskActionType>;
  updatedAt: Generated<Timestamp | null>;
}

export interface TaskChecklistItems {
  categoryKey: Generated<string>;
  completedAt: Timestamp | null;
  completedBy: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: string;
  isCompleted: Generated<boolean>;
  sortOrder: Generated<number>;
  taskId: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface TaskDependencies {
  createdAt: Generated<Timestamp | null>;
  dependencyType: Generated<DependencyType>;
  dependsOnTaskId: string;
  id: Generated<string>;
  taskId: string;
}

export interface TaskParticipants {
  createdAt: Generated<Timestamp | null>;
  id: string;
  memberId: string;
  role: Generated<TaskParticipantRole>;
  taskId: string;
}

export interface Tasks {
  assignedTeamId: string | null;
  assigneeId: string | null;
  createdAt: Generated<Timestamp | null>;
  endDate: Timestamp | null;
  id: string;
  name: string;
  priority: Generated<TaskPriority | null>;
  progress: Generated<number | null>;
  projectId: string;
  shift: Generated<TaskShift | null>;
  stageId: string;
  startDate: Timestamp | null;
  status: Generated<TaskStatus | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface TeamGroupMembers {
  createdAt: Generated<Timestamp>;
  id: string;
  memberId: string;
  teamId: string;
}

export interface TeamMembers {
  capacityHours: Generated<Numeric | null>;
  createdAt: Generated<Timestamp | null>;
  email: string | null;
  employmentType: Generated<EmploymentType>;
  fullName: string | null;
  id: string;
  initials: Generated<string | null>;
  name: string;
  nickname: string | null;
  phone: string | null;
  role: Generated<string | null>;
  status: Generated<TeamMemberStatus>;
  userId: number | null;
}

export interface Teams {
  createdAt: Generated<Timestamp>;
  id: string;
  name: string;
  sectorId: string | null;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp>;
  passwordHash: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp>;
}

export interface V8Campaigns {
  id: Generated<string>;
  direcao: string | null;
  experiencia: string | null;
  objetivoPrimario: string | null;
  segmentoPublico: string | null;
  createdAt: Generated<Timestamp | null>;
}

export interface V8Modules {
  id: Generated<string>;
  campaignId: string;
  bloco: number | null;
  nome: string;
  descricao: string | null;
  status: Generated<string | null>;
  owner: string | null;
  cost: Numeric | null;
  dueDate: Timestamp | null;
  ok: Generated<boolean | null>;
  okTrigger: string | null;
  createdAt: Generated<Timestamp | null>;
}

export interface V8Gates {
  id: Generated<string>;
  campaignId: string;
  name: string;
  critical: Generated<boolean | null>;
  ok: Generated<boolean | null>;
  artifact: string | null;
  createdAt: Generated<Timestamp | null>;
}

export interface DB {
  activityLogs: ActivityLogs;
  brands: Brands;
  budgetItems: BudgetItems;
  campaignPosts: CampaignPosts;
  campaigns: Campaigns;
  executions: Executions;
  initiatives: Initiatives;
  loginAttempts: LoginAttempts;
  modules: Modules;
  moduleStages: ModuleStages;
  moduleTasks: ModuleTasks;
  planningBaseItems: PlanningBaseItems;
  planningBases: PlanningBases;
  projectChecklistItems: ProjectChecklistItems;
  projects: Projects;
  projectStages: ProjectStages;
  sectorMembers: SectorMembers;
  sectors: Sectors;
  sessions: Sessions;
  taskActions: TaskActions;
  taskChecklistItems: TaskChecklistItems;
  taskDependencies: TaskDependencies;
  taskParticipants: TaskParticipants;
  tasks: Tasks;
  teamGroupMembers: TeamGroupMembers;
  teamMembers: TeamMembers;
  teams: Teams;
  userPasswords: UserPasswords;
  users: Users;
  v8Campaigns: V8Campaigns;
  v8Modules: V8Modules;
  v8Gates: V8Gates;
}

// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const CampaignStatusArrayValues: [CampaignStatus, ...CampaignStatus[]] = ["active","approved","completed","draft"];
export const CampaignTypeArrayValues: [CampaignType, ...CampaignType[]] = ["awareness","brand_engagement","corporate_event","product_launch","seasonal_promotion"];
export const ProjectStatusArrayValues: [ProjectStatus, ...ProjectStatus[]] = ["active","cancelled","completed","paused"];
export const TaskStatusArrayValues: [TaskStatus, ...TaskStatus[]] = ["blocked","completed","in_progress","open","overdue","standby"];
export const TaskPriorityArrayValues: [TaskPriority, ...TaskPriority[]] = ["critical","high","low","medium"];
export const BudgetItemStatusArrayValues: [BudgetItemStatus, ...BudgetItemStatus[]] = ["contracted","paid","pending"];
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const ProjectCategoryArrayValues: [ProjectCategory, ...ProjectCategory[]] = ["custom","event","implementation","infrastructure","maintenance","operational","strategic","travel"];
export const TaskActionTypeArrayValues: [TaskActionType, ...TaskActionType[]] = ["approve","confirm_completion","custom","make_payment","review","sign_document"];
export const TaskActionStatusArrayValues: [TaskActionStatus, ...TaskActionStatus[]] = ["completed","in_progress","pending","rejected"];
export const TaskParticipantRoleArrayValues: [TaskParticipantRole, ...TaskParticipantRole[]] = ["assignee","observer","owner","reviewer"];
export const ActivityActionArrayValues: [ActivityAction, ...ActivityAction[]] = ["assigned","commented","completed","created","deleted","status_changed","updated"];
export const StageStatusArrayValues: [StageStatus, ...StageStatus[]] = ["completed","in_progress","pending"];
export const DependencyTypeArrayValues: [DependencyType, ...DependencyType[]] = ["finish_to_finish","finish_to_start","start_to_finish","start_to_start"];
export const ExecutionStatusArrayValues: [ExecutionStatus, ...ExecutionStatus[]] = ["completed","in_progress","paused"];
export const SectorMemberRoleArrayValues: [SectorMemberRole, ...SectorMemberRole[]] = ["agente","responsavel"];
export const TeamMemberStatusArrayValues: [TeamMemberStatus, ...TeamMemberStatus[]] = ["active","pending_registration"];
export const EmploymentTypeArrayValues: [EmploymentType, ...EmploymentType[]] = ["clt","contract_service","hourly_contractor"];
export const InitiativeStatusArrayValues: [InitiativeStatus, ...InitiativeStatus[]] = ["aprovada","concluida","em_andamento","recusada","solicitada"];
export const TaskShiftArrayValues: [TaskShift, ...TaskShift[]] = ["afternoon","morning","night"];
export const PlanningBaseTypeArrayValues: [PlanningBaseType, ...PlanningBaseType[]] = ["annual","custom","quarterly"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.