import React, { useMemo } from "react";
import { Palette } from "lucide-react";
import { CriarMaterialSimple } from "./criar-material-simple";
import { InfoNote } from "./info-note";
import { useTranslations } from "../../i18n/use-translations";

export function ComunicacaoVisual() {
  const { tGroup, language } = useTranslations();
  const tools = useMemo(() => tGroup('tools'), [tGroup, language]);
  
  return (
    <div className="p-6 max-w-[1400px] mx-auto">
      <div className="space-y-6">
        <div className="space-y-2">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-primary/10">
              <Palette className="w-6 h-6 text-primary" />
            </div>
            <h1 className="text-3xl font-bold">{tools.visualCommunicationTitle}</h1>
          </div>
          <p className="text-muted-foreground mt-1">
            {tools.visualCommunicationDescription}
          </p>
        </div>

        {/* Info Note */}
        <InfoNote title={tools.documentsTip}>
          {tools.visualCommunicationAutoGenerated}
        </InfoNote>

        {/* Motor de Materiais */}
        <CriarMaterialSimple categoryFilter="comunicacao" />
      </div>
    </div>
  );
}